plugins { id "com.android.library" }
android {
    namespace "com.jellyfinforrayneo.video"
    compileSdk 35
    defaultConfig { minSdk 26 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions { unitTests.returnDefaultValues = true }
    lint { abortOnError true }
}
dependencies {
    api "androidx.media3:media3-exoplayer:1.5.1"
    implementation "androidx.media3:media3-exoplayer-hls:1.5.1"
    testImplementation "junit:junit:4.13.2"
}
